# LDA OR Latent Dirchlet Allocation

LDA Approach is a unsupervised leraning algorithm to identify the topics that are hidden in a documents.
Here we are trying to extarct the topic which related to MG hector car that is newly launched into the market.
LDA Would able to extract the important topics from the customer reviews

In [107]:
import pandas as pd

In [108]:
df = pd.read_csv("E:\\Text_Analytics\\MG_Hector.csv",header=0,encoding = 'unicode_escape')

In [109]:
df.head()

Review
0  From whatever little information is available ...
1  However, this is a Chinese brand and they will...
2  I doubt the future of MG in India with their r...
3  However, from what I've read so far, the Baoju...
4  MG Hector petrol engine details revealed, seem...

# Preprocessing

In [110]:
#importing the count vectorizer 
from sklearn.feature_extraction.text import CountVectorizer

In [111]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [112]:
dtm = cv.fit_transform(df['Review'])

In [113]:
dtm

<40x198 sparse matrix of type '<class 'numpy.int64'>'
	with 567 stored elements in Compressed Sparse Row format>

Here we are converted the reviews into matrix of columns using the count vectorizer.
Let's import the LDA to perform topic identifying

# LDA

In [114]:
from sklearn.decomposition import LatentDirichletAllocation

In [115]:
#We need to decide how many topics that we need to identify from LDA analyisis and we need to specify in n_components
#Here I have tawken 5 topic
LDA = LatentDirichletAllocation(n_components=3,random_state=42)

In [116]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='batch', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_components=3, n_jobs=None, n_topics=None, perp_tol=0.1,
             random_state=42, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

# Getting the words from the reviews

In [117]:
len(cv.get_feature_names())

198

In [118]:
#getting the random words
import random
for i in range(10):
    random_word_id = random.randint(0,190)
    print(cv.get_feature_names()[random_word_id])

especially
product
comfortable
showroom
soon
vehicles
guess
car
details
petrol


# Identifying the top words in a Topic

In [119]:
len(LDA.components_)

3

As we decided earlier we are idebtifying 5 topics from the LDA Analyzis

In [120]:
LDA.components_

array([[ 0.3337817 ,  0.33357623,  1.34002325,  0.33363096,  0.33372938,
         0.33357326,  2.33169144,  0.33354517,  0.3348114 ,  0.33374237,
         0.33354481,  0.33360048,  7.33283598,  2.20885037,  0.33347785,
         0.33382672,  0.55276529,  3.31404104,  0.33430821,  0.47980683,
         1.3682048 ,  0.33379657,  0.33399717,  0.33364991,  0.78879325,
         0.8350769 ,  1.32575089,  0.33345906,  1.34627516,  5.25459734,
         0.34301075,  0.33353345,  0.3334314 ,  0.33344732,  0.3335305 ,
         3.3635059 ,  0.36385051,  0.33348338,  0.33370876,  3.33224831,
         0.33344604,  0.33429715,  0.33341261,  0.33346017,  0.33354444,
         1.33557726,  1.33848773,  0.33354517,  3.33217886,  0.33345906,
         1.32956219,  2.34608462,  0.33368743,  1.335615  ,  0.33363478,
         2.24474108,  0.3334314 ,  0.33373309,  4.32392023,  0.33346642,
         0.34752433,  0.33358204,  2.33297453,  0.3343559 ,  0.3343559 ,
         2.32404912,  0.3337232 ,  0.33356461,  0.4

Above we are extracting the probability of words in a topic. here we have 5 topic and each word has probability for each topic.
Now we need to find out the highest probability of words in a topic.

In [121]:
len(LDA.components_[0])

198

In [122]:
first_topic = LDA.components_[0]

In [123]:
#argsort() return the indexes in sorted order from low probability to higher probabilty
first_topic.argsort()

array([181,  42, 134, 153,  56,  71,  32, 184,  40,  33,  78, 192, 123,
        27, 116,  73,  49, 176,  43, 132,  59, 186, 188, 122, 118,  14,
       157,  37, 114, 168, 169, 173, 165, 130,  96,  34, 111,  88,  31,
       170,  44,  10,  47, 150, 131, 141,   7,  67,   5, 175,   1, 164,
        61, 142,  11,  81, 161,  91, 187,  74,  95, 143,   3,  54,  85,
        86,  83,  23, 145, 102, 162, 151,  52, 193, 104,  38, 133,  66,
       156,   4, 196,  57, 154,   9, 146, 195,   0,  21, 179, 113, 180,
        15,  87, 183, 107, 177,  72,  93, 158,  89, 121, 129,  22, 155,
       138, 149, 152,  41,  18, 100,  64,  63, 159, 185, 105,   8, 148,
       112, 144,  30,  60, 182,  84,  77,  79,  82,  90,  36, 127,  94,
       194, 190, 172, 117,  75,  68,  19,  69, 140,  16,  24,  25,  98,
       110,  26, 137,  50, 163,  99, 136, 106, 124, 171,  45,  53, 128,
       108, 135, 147,  46, 101,   2, 125,  28,  20,  97,  70, 189, 120,
        13,  55, 160, 197,  92, 119,  76, 191, 167,  65, 115,   

In [124]:
#word that least able to expalin the topic is index'124'
first_topic[124]

1.3341187231102016

In [125]:
#Word which has high probability ans can explain this topic mostly is index position '139'
first_topic[139]

4.282526057195967

In [126]:
# Top 10 words for this topic:
top_word_indices = first_topic.argsort()[-10:]

In [127]:
#Now we have got index locatio of top ten words. Now we can pull corresponding words to get the topic understanding
for index in top_word_indices:
    print(cv.get_feature_names()[index])

deciding
creta
torque
pricing
factor
compass
tucson
bracket
support
lumbar


# Identify the top 15 words for each topics

In [128]:
for i,topic in enumerate(LDA.components_):
    print(f'The top 10 words of topic #{i}')
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

The top 10 words of topic #0
['helps', 'drives', 'long', 'cars', 'don', 'deciding', 'creta', 'torque', 'pricing', 'factor', 'compass', 'tucson', 'bracket', 'support', 'lumbar']




The top 10 words of topic #1
['said', 'vehicle', 'jeep', 'guess', 'td', 'wait', 'better', 'diesel', 'city', 'drive', 'kmpl', 'dct', 'good', 'test', 'petrol']




The top 10 words of topic #2
['country', 'like', 'just', 'industry', 'feature', 'point', 'speed', 'china', 'brand', 'market', 'chinese', 'petrol', 'car', 'hector', 'mg']






### First Topic : 

First topic tells about factors that most decides in MG hector

It tells about the Lumbar support which is laking in MG hector

It also tells about the pricing of the car

### Second Topic : Performance of the MG Hector

Second topic more talks about the performance of the MG hector

The TOPIC is about the milege, perfomance of petrol and diesel variants , city drive etc


### Third Topic : MG Hector as a China Car

This topic mainly identifyies the talks that related that Hector as a China Car.

Some of the customers are indicating MG hector as a Chinese product and this will give negartive impact in indian markets

# Combining with Original Data and identifyies Topics of Each Review

In [129]:
dtm.shape

(40, 198)

In [130]:
dtm

<40x198 sparse matrix of type '<class 'numpy.int64'>'
	with 567 stored elements in Compressed Sparse Row format>

In [135]:
#Transformming entire matrix of data terms and getting their probability of each topics
topic_results = LDA.transform(dtm)

In [136]:
topic_results.shape

(40, 3)

In [137]:
#getting the probability scores of first review.
topic_results[0]

array([0.01973863, 0.02079774, 0.95946363])

In [138]:
#Getting the highest probabilty and the first review identified as topic 3
topic_results[0].argmax()

2

In [139]:
df.head()

Review
0  From whatever little information is available ...
1  However, this is a Chinese brand and they will...
2  I doubt the future of MG in India with their r...
3  However, from what I've read so far, the Baoju...
4  MG Hector petrol engine details revealed, seem...

In [140]:
topic_results.argmax(axis=1)

array([2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0,
       2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1], dtype=int64)

In [141]:
df['Topic'] = topic_results.argmax(axis=1)

In [153]:
df.head(10)

Review  Topic
0  From whatever little information is available ...      2
1  However, this is a Chinese brand and they will...      2
2  I doubt the future of MG in India with their r...      2
3  However, from what I've read so far, the Baoju...      2
4  MG Hector petrol engine details revealed, seem...      2
5  Look at the torque figures. That would more th...      0
6  This one is a definite Creta rival. 2019 seems...      0
7  14-118 hp and 150 Nm of torque but with a 4-sp...      0
8  The MG 3 looks uncannily similar to the Santro...      2
9  Quality and fit and finish are superb and are ...      1